name: SQL Linter for Modified Schema

on:
  push:
    branches: [main]

jobs:
  SQLLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Lint Modified SQL Schema
        run: sqlfluff lint $GITHUB_WORKSPACE/RelationDB_DetailedDataSchemaModified.sql --dialect postgres
