name: Print Software Versions

on:
  push:
    branches: [main]

jobs:
  PrintClientAndServerSoftwareVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Operating System (Client)
        run: uname -a

      - name: Install Vue CLI
        run: npm install -g @vue/cli

      - name: Print Web Framework (Vue.js)
        run: vue --version

      - name: Print Node.js Version (Server)
        run: node --version

  PrintDatabaseServerVersion:
    runs-on: ubuntu-latest
    needs: [PrintClientAndServerSoftwareVersions]
    steps:
      - name: Install PostgreSQL
        run: |
          sudo apt update
          sudo apt install -y postgresql

      - name: Start PostgreSQL service
        run: |
          sudo service postgresql start

      - name: Print PostgreSQL Version
        run: |
          psql --version

      - name: Print PostgreSQL Server Version
        run: |
          sudo -u postgres psql -c "SELECT version();"


      - name: Check PostgreSQL server version
        run: |
          echo "PostgreSQL server version:"
          sudo -u postgres psql -c "SELECT version();"
